name: Backend test
on:
  push:
    branches: cicd-new

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Write pk.json from secrets
        working-directory: backend
        run: |
          echo "${{ secrets.PK_JSON }}" | base64 --decode > pk.json
        env:
          PK_JSON: ${{ secrets.PK_JSON }}
      - name: Run Pytest
        run: |
          cd backend
          pytest tests
      - name: Delete pk.json
        run: |
          rm backend/pk.json
