name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend  # run commands from frontend

    strategy:
      matrix:
        spec-file: [1.cy.js]  # add test files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'
          cache: 'npm'  # cache node modules

      - name: Install dependencies
        run: npm ci  # clean install (faster)

      - name: Run Cypress tests
        run: |
          npx cypress run \
            --config-file cypress.config.js \
            --spec "cypress/e2e/${{ matrix.spec-file }}"
