name: Unit Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false  # continue even if one test fails
      matrix:
        spec-file: [1.cy.js]  # add more if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  #v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'
          cache: 'npm'  # cache dependencies

      - name: Install dependencies
        working-directory: ./frontend  # install from frontend/
        run: npm ci --no-audit  # clean install (faster than npm install)

      - name: Run Cypress tests
        working-directory: ./frontend  #  from frontend/
        run: |
          npx cypress run \
            --config-file cypress.config.js \
            --spec "cypress/e2e/${{ matrix.spec-file }}" \
            --record false  # 
