name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Frontend directory contents:"
          ls -la frontend/

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci --no-audit

      - name: Verify Cypress
        working-directory: ./frontend
        run: npx cypress verify

      - name: Start server and run tests
        working-directory: ./frontend
        run: |
          npm run dev &
          SERVER_PID=$!
          
          # Wait for server
          npx wait-on http://localhost:3000
          
          # Run tests
          npx cypress run --browser chrome --config baseUrl=http://localhost:3000 || TEST_RESULT=$?
          
          kill $SERVER_PID
          exit ${TEST_RESULT:-0}
        env:
          PORT: 3000
          NODE_ENV: test

      - name: Build project
        working-directory: ./frontend
        run: npm run build

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-failures
          path: |
            frontend/cypress/screenshots
            frontend/cypress/videos
