name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # LTS version recommended
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress
        run: npx cypress verify

      - name: Start server and run tests
        run: |
          # Start server in background
          npm run dev &
          SERVER_PID=$!
          
          # Wait for server (replaces wait-on)
          echo "Waiting for server to start..."
          for i in {1..10}; do
            if curl -s http://localhost:3000 >/dev/null; then
              echo "Server is up!"
              break
            fi
            sleep 3
          done
          
          # Run Cypress tests
          npx cypress run --browser chrome --config baseUrl=http://localhost:3000 || TEST_RESULT=$?
          
          # Kill server
          kill $SERVER_PID
          exit ${TEST_RESULT:-0}
        env:
          PORT: 3000
          NODE_ENV: test

      - name: Build production bundle
        run: npm run build

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            cypress/logs
          retention-days: 1
